import type { Metadata } from "next";
import "../globals.css";
import { AuthProvider } from "@/context/AuthContext";
import LayoutWrapper from "./LayoutWrapper";
import { Toaster } from "sonner";
import { CartProvider } from "@/context/CartContext";

export const metadata: Metadata = {
	title: "Velora",
	description: "Generated by create next app",
};

export default function MainLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<CartProvider>
				<LayoutWrapper>{children}</LayoutWrapper>
				<Toaster richColors closeButton />
			</CartProvider>
		</AuthProvider>
	);
}
